[[constraint]]
  name = "github.com/golangci/revgrep"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "sourcegraph.com/sourcegraph/go-diff"

[[constraint]]
  name = "github.com/kisielk/errcheck"
  branch = "master"
  source = "github.com/golangci/errcheck"

[[constraint]]
  name = "github.com/golangci/govet"
  branch = "master"

[[constraint]]
  name = "github.com/mibk/dupl"
  branch = "master"
  source = "github.com/golangci/dupl"

[[constraint]]
  name = "mvdan.cc/unparam"
  branch = "fix-crash-on-nil-constant"
  source = "github.com/golangci/unparam"

[[constraint]]
  name = "github.com/GoASTScanner/gas"
  branch = "master"
  source = "github.com/golangci/gas"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-ps"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/unconvert"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/go-misc"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/goconst"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/check"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/gocyclo"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/gofmt"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/maligned"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/ineffassign"

[[constraint]]
  branch = "master"
  name = "github.com/OpenPeeDeeP/depguard"

[[constraint]]
  branch = "master"
  name = "golang.org/x/tools"
  source = "github.com/golangci/tools"

[[constraint]]
  branch = "master"
  name = "honnef.co/go/tools"
  source = "github.com/golangci/go-tools"
