# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/golangci/revgrep"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "sourcegraph.com/sourcegraph/go-diff"

[[constraint]]
  name = "github.com/kisielk/errcheck"
  branch = "master"
  source = "github.com/golangci/errcheck"

[[constraint]]
  name = "github.com/golangci/govet"
  branch = "master"

[[constraint]]
  name = "github.com/mibk/dupl"
  branch = "master"
  source = "github.com/golangci/dupl"

[[constraint]]
  name = "mvdan.cc/interfacer"
  branch = "master"
  source = "github.com/golangci/interfacer"

[[constraint]]
  name = "github.com/GoASTScanner/gas"
  branch = "master"
  source = "github.com/golangci/gas"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-ps"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/go-tools"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/unconvert"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/go-misc"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/goconst"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/check"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/gocyclo"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/gofmt"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/maligned"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/ineffassign"

[[override]]
  branch = "master"
  name = "github.com/golangci/lint"

[[constraint]]
  branch = "master"
  name = "github.com/OpenPeeDeeP/depguard"
