name: "Post release"
on:
  release:
    types:
      - published

jobs:
  update-docs:
    name: "Update readme"
    continue-on-error: true
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GOLANGCI_LINT_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          # https://github.com/actions/setup-go#supported-version-syntax
          # ex:
          # - 1.18beta1 -> 1.18.0-beta.1
          # - 1.18rc1 -> 1.18.0-rc.1
          go-version: '1.22'
      - uses: actions/setup-node@v4
        with:
          node-version: "15"
          check-latest: true

      - name: npm install
        working-directory: .github/contributors
        run: npm install

      - name: Update Contributors list
        run: make update_contributors_list # may take more than 1 hour

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          base: master
          token: ${{ secrets.GOLANGCI_LINT_TOKEN }}
          branch-suffix: timestamp
          title: "docs: update documentation"
          delete-branch: true

  update-gha-assets:
    name: "Update GitHub Action assets"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GOLANGCI_LINT_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          # https://github.com/actions/setup-go#supported-version-syntax
          # ex:
          # - 1.18beta1 -> 1.18.0-beta.1
          # - 1.18rc1 -> 1.18.0-rc.1
          go-version: '1.22'

      - name: Update GitHub Action config
        run: make assets/github-action-config.json

      - name: Update reference files
        run: cp .golangci.next.reference.yml .golangci.reference.yml

      - name: Update JSON schema files
        run: cp jsonschema/golangci.next.jsonschema.json jsonschema/golangci.jsonschema.json

      - name: Update information
        run: make website_dump_info

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          base: master
          token: ${{ secrets.GOLANGCI_LINT_TOKEN }}
          branch-suffix: timestamp
          title: "docs: update GitHub Action assets"
          delete-branch: true

  update-assets:
    name: "Update documentation assets"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GOLANGCI_LINT_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          # https://github.com/actions/setup-go#supported-version-syntax
          # ex:
          # - 1.18beta1 -> 1.18.0-beta.1
          # - 1.18rc1 -> 1.18.0-rc.1
          go-version: '1.22'

      - name: Update reference files
        run: cp .golangci.next.reference.yml .golangci.reference.yml

      - name: Update JSON schema files
        run: cp jsonschema/golangci.next.jsonschema.json jsonschema/golangci.jsonschema.json

      - name: Update information
        run: make website_dump_info

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          base: master
          token: ${{ secrets.GOLANGCI_LINT_TOKEN }}
          branch-suffix: timestamp
          title: "docs: update documentation assets"
          delete-branch: true
